create table 	h1b_fy2009_1_stg 	(
SUBMITTED_DATE	character varying(2000),	
CASE_NO	character varying(2000),	
PROGRAM_DESIGNATION	character varying(2000),	
EMPLOYER_NAME	character varying(2000),	
EMPLOYER_ADDRESS1	character varying(2000),	
EMPLOYER_ADDRESS2	character varying(2000),	
EMPLOYER_CITY	character varying(2000),	
EMPLOYER_STATE	character varying(2000),	
EMPLOYER_COUNTY	character varying(2000),	
EMPLOYER_POSTAL_CODE	character varying(2000),	
NBR_IMMIGRANTS	character varying(2000),	
BEGIN_DATE	character varying(2000),	
END_DATE	character varying(2000),	
JOB_TITLE	character varying(2000),	
DOL_DECISION_DATE	character varying(2000),	
OCCUPATIONAL_CODE	character varying(2000),	
OCCUPATIONAL_TITLE	character varying(2000),	
APPROVAL_STATUS	character varying(2000),	
WAGE_RATE_1	character varying(2000),	
RATE_PER_1	character varying(2000),	
MAX_RATE_1	character varying(2000),	
PART_TIME_1	character varying(2000),	
CITY_1	character varying(2000),	
STATE_1	character varying(2000),	
PREVAILING_WAGE_1	character varying(2000),	
WAGE_SOURCE_1	character varying(2000),	
YR_SOURCE_PUB_1	character varying(2000),	
OTHER_WAGE_SOURCE_1	character varying(2000),	
WAGE_RATE__2	character varying(2000),	
RATE_PER_2	character varying(2000),	
MAX_RATE_2	character varying(2000),	
PART_TIME_2	character varying(2000),	
CITY_2	character varying(2000),	
STATE_2	character varying(2000),	
PREVAILING_WAGE_2	character varying(2000),	
WAGE_SOURCE_2	character varying(2000),	
YR_SOURCE_PUB_2	character varying(2000),	
OTHER_WAGE_SOURCE_2	character varying(2000),	
WITHDRAWN	character varying(2000)	
		);
		
copy 	h1b_fy2009_1_stg (
SUBMITTED_DATE	,
CASE_NO	,
PROGRAM_DESIGNATION	,
EMPLOYER_NAME	,
EMPLOYER_ADDRESS1	,
EMPLOYER_ADDRESS2	,
EMPLOYER_CITY	,
EMPLOYER_STATE	,
EMPLOYER_COUNTY	,
EMPLOYER_POSTAL_CODE	,
NBR_IMMIGRANTS	,
BEGIN_DATE	,
END_DATE	,
JOB_TITLE	,
DOL_DECISION_DATE	,
OCCUPATIONAL_CODE	,
OCCUPATIONAL_TITLE	,
APPROVAL_STATUS	,
WAGE_RATE_1	,
RATE_PER_1	,
MAX_RATE_1	,
PART_TIME_1	,
CITY_1	,
STATE_1	,
PREVAILING_WAGE_1	,
WAGE_SOURCE_1	,
YR_SOURCE_PUB_1	,
OTHER_WAGE_SOURCE_1	,
WAGE_RATE__2	,
RATE_PER_2	,
MAX_RATE_2	,
PART_TIME_2	,
CITY_2	,
STATE_2	,
PREVAILING_WAGE_2	,
WAGE_SOURCE_2	,
YR_SOURCE_PUB_2	,
OTHER_WAGE_SOURCE_2	,
WITHDRAWN	)
FROM 'D:\AppData\oflc\raw_h1b\csv\H1B_FY2009_1.csv' DELIMITER ',' CSV HEADER;