create table h1b_performance_reporting_temp 
as
select  CASE_NUMBER, CASE_STATUS,CASE_SUBMITTED,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE, EMPLOYER_STATE,JOB_TITLE,SOC_CODE,SOC_NAME,NAICS_CODE,FULL_TIME_POSITION,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL, '2019' as YYYY from h1b_fy2019_stg 
union
select  CASE_NUMBER, CASE_STATUS,CASE_SUBMITTED,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE, EMPLOYER_STATE,JOB_TITLE,SOC_CODE,SOC_NAME,NAICS_CODE,FULL_TIME_POSITION,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL, '2018' as YYYY from h1b_fy2018_stg 
union
select  CASE_NUMBER, CASE_STATUS,CASE_SUBMITTED,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE, EMPLOYER_STATE,JOB_TITLE,SOC_CODE,SOC_NAME,NAICS_CODE,FULL_TIME_POSITION,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL, '2017' as YYYY from h1b_fy2017_stg 
union
select  CASE_NUMBER, CASE_STATUS,CASE_SUBMITTED,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE, EMPLOYER_STATE,JOB_TITLE,SOC_CODE,SOC_NAME,NAIC_CODE as NAICS_CODE,FULL_TIME_POSITION,'' as PREVAILING_WAGE,PW_UNIT_OF_PAY,'' as PW_WAGE_LEVEL, '2016' as YYYY from h1b_fy2016_stg 
union 
select CASE_NUMBER, CASE_STATUS,CASE_SUBMITTED,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE, EMPLOYER_STATE,JOB_TITLE,SOC_CODE,SOC_NAME,NAIC_CODE as NAICS_CODE,FULL_TIME_POSITION,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL, '2015' as YYYY from h1b_fy2015_stg  
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,FULL_TIME_POS AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2014' as YYYY from h1b_fy2014_stg  
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,FULL_TIME_POS AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2013' as YYYY from h1b_fy2013_stg  
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,FULL_TIME_POS AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2012' as YYYY from h1b_fy2012_stg  
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,FULL_TIME_POS AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2011' as YYYY from h1b_fy2011_stg  
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,'' AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2010' as YYYY from h1b_fy2010_stg 
union
select LCA_CASE_NUMBER as CASE_NUMBER, STATUS as  CASE_STATUS,LCA_CASE_SUBMIT AS CASE_SUBMITTED, LCA_CASE_EMPLOYMENT_START_DATE AS EMPLOYMENT_START_DATE, LCA_CASE_EMPLOYMENT_END_DATE AS EMPLOYMENT_END_DATE,LCA_CASE_EMPLOYER_STATE AS  EMPLOYER_STATE, LCA_CASE_JOB_TITLE AS JOB_TITLE, LCA_CASE_SOC_CODE AS SOC_CODE, LCA_CASE_SOC_NAME AS SOC_NAME,LCA_CASE_NAICS_CODE as NAICS_CODE,'' AS FULL_TIME_POSITION,PW_1 AS PREVAILING_WAGE,PW_UNIT_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2009' as YYYY from h1b_fy2009_2_stg  
union
select CASE_NO as CASE_NUMBER, APPROVAL_STATUS as  CASE_STATUS,SUBMITTED_DATE AS CASE_SUBMITTED, BEGIN_DATE AS EMPLOYMENT_START_DATE, END_DATE AS EMPLOYMENT_END_DATE,STATE_1 AS  EMPLOYER_STATE, OCCUPATIONAL_TITLE AS JOB_TITLE, OCCUPATIONAL_code AS SOC_CODE, '' AS SOC_NAME,'' as NAICS_CODE,'' AS FULL_TIME_POSITION,PREVAILING_WAGE_1 AS PREVAILING_WAGE,RATE_PER_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2009' as YYYY from h1b_fy2009_1_stg  
union
select CASE_NO as CASE_NUMBER, APPROVAL_STATUS as  CASE_STATUS,SUBMITTED_DATE AS CASE_SUBMITTED, BEGIN_DATE AS EMPLOYMENT_START_DATE, END_DATE AS EMPLOYMENT_END_DATE,STATE_1 AS  EMPLOYER_STATE, OCCUPATIONAL_TITLE AS JOB_TITLE, '' AS SOC_CODE, '' AS SOC_NAME,'' as NAICS_CODE,'' AS FULL_TIME_POSITION,PREVAILING_WAGE_1 AS PREVAILING_WAGE,RATE_PER_1 AS PW_UNIT_OF_PAY,'' AS PW_WAGE_LEVEL, '2008' as YYYY from h1b_fy2008_stg  



﻿










